spring:
  application:
    name: exp2-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/selflearn?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: exp1
    password: 114514
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8879

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
